server:
  port: 8080
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/tourism}
    driverClassName: "org.postgresql.Driver"
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0


  mail:
    host: smtp.gmail.com
    port: 587
    username: thoai12309@gmail.com
    password: ldyb bfmi tsia hvsn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

cloudinary:
  cloud-name: dnt8vx1at
  api-key: 939641688935771
  api-secret: WPzZSJqg4MVvHKUuvPFeHL981J0

app:
  cors:
    allowed-origins: http://localhost:3000, http://mydomain.com
  frontend:
    url: http://localhost:3000

vnpay:
  tmn-code: 2Z2285VA
  hash-secret: UUN1JEF3JCWQIRCMN76Q34RUQLRI4Q1J
  api-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/payment/vnpay-callback
  version: 2.1.0
  command: pay
  order-type: other



